import http from 'node:http'
import crypto from 'node:crypto'
import { Pool } from 'pg'

const VERSION = '2.0.0'
const PORT = Number(process.env.PORT || 8787)
const DB = process.env.DATABASE_URL || ''
const JWT_SECRET = process.env.JWT_SECRET || ''
const AUTH_LIMIT_PER_15M = Number(process.env.AUTH_LIMIT_PER_15M || 20)
const API_LIMIT_PER_MIN = Number(process.env.API_LIMIT_PER_MIN || 90)
const CENTS_PER_CREDIT = Math.max(1, Number(process.env.STRIPE_CENTS_PER_CREDIT || 2))
const CREDIT_COST = Object.freeze({ openai: 4, anthropic: 5, gemini: 3, xai: 5, deepseek: 2, openrouter: 4 })
if (!DB) throw new Error('DATABASE_URL is required')
if (JWT_SECRET.length < 32) throw new Error('JWT_SECRET must contain at least 32 characters')
const pool = new Pool({ connectionString: DB, ssl: /sslmode=require/i.test(DB) ? { rejectUnauthorized: false } : undefined })

const configuredProviders = () => [
  ['openai', process.env.OPENAI_API_KEY], ['anthropic', process.env.ANTHROPIC_API_KEY], ['gemini', process.env.GEMINI_API_KEY],
  ['xai', process.env.XAI_API_KEY], ['deepseek', process.env.DEEPSEEK_API_KEY], ['openrouter', process.env.OPENROUTER_API_KEY]
].filter(([, key]) => Boolean(key)).map(([id]) => id)

function securityHeaders(extra = {}) { return { 'x-content-type-options':'nosniff','x-frame-options':'DENY','referrer-policy':'no-referrer','permissions-policy':'camera=(), microphone=(), geolocation=()','cache-control':'no-store', ...extra } }
function json(res, status, body, headers = {}) { res.writeHead(status, securityHeaders({ 'content-type':'application/json; charset=utf-8', ...headers })); res.end(JSON.stringify(body)) }
function b64url(input) { return Buffer.from(input).toString('base64url') }
function safeEqualText(a, b) { const aa=Buffer.from(String(a)), bb=Buffer.from(String(b)); return aa.length===bb.length && crypto.timingSafeEqual(aa,bb) }
function signToken(userId, ttl = 60*60*24*30) { const now=Math.floor(Date.now()/1000), h=b64url(JSON.stringify({alg:'HS256',typ:'JWT'})), p=b64url(JSON.stringify({sub:userId,exp:now+ttl,iat:now})), sig=crypto.createHmac('sha256',JWT_SECRET).update(`${h}.${p}`).digest('base64url'); return `${h}.${p}.${sig}` }
function verifyToken(token) { const parts=String(token||'').split('.'); if(parts.length!==3)return'';const expected=crypto.createHmac('sha256',JWT_SECRET).update(`${parts[0]}.${parts[1]}`).digest('base64url');if(!safeEqualText(expected,parts[2]))return'';try{const p=JSON.parse(Buffer.from(parts[1],'base64url'));return p.exp>Date.now()/1000?String(p.sub||''):''}catch{return''} }
function authUser(req) { const v=req.headers.authorization||''; return verifyToken(v.startsWith('Bearer ')?v.slice(7):'') }
async function body(req,max=18*1024*1024){const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>max)throw Object.assign(new Error('Payload too large'),{status:413});chunks.push(chunk)}const raw=Buffer.concat(chunks).toString('utf8');try{return raw?JSON.parse(raw):{}}catch{throw Object.assign(new Error('Invalid JSON'),{status:400})}}
function hashPassword(password,salt){return crypto.scryptSync(password,salt,64).toString('hex')}
function passwordMatches(password,salt,hash){return safeEqualText(hashPassword(password,salt),hash)}
function validateEmail(v){const email=String(v||'').trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>254)throw Object.assign(new Error('Invalid email'),{status:400});return email}
function validatePassword(v){const p=String(v||'');if(p.length<10||p.length>256)throw Object.assign(new Error('Password must be 10-256 characters'),{status:400});return p}
function providerCreditCost(provider){const cost=CREDIT_COST[provider];if(!cost)throw Object.assign(new Error('Provider is not eligible for Cloud credits'),{status:400});return cost}

const rateBuckets = new Map()
function rateLimit(key, max, windowMs){const now=Date.now();const current=rateBuckets.get(key);if(!current||current.resetAt<=now){rateBuckets.set(key,{count:1,resetAt:now+windowMs});return 0}current.count++;if(current.count<=max)return 0;return Math.max(1,current.resetAt-now)}
function clientIp(req){return String(req.headers['x-forwarded-for']||req.socket.remoteAddress||'unknown').split(',')[0].trim().slice(0,128)}
function enforceRate(key,max,windowMs){const retry=rateLimit(key,max,windowMs);if(retry)throw Object.assign(new Error('Too many requests'),{status:429,retryAfterMs:retry})}
setInterval(()=>{const now=Date.now();for(const [k,v] of rateBuckets)if(v.resetAt<now-60_000)rateBuckets.delete(k)},5*60_000).unref()

async function getUser(userId){const{rows}=await pool.query(`SELECT u.id,u.email,u.display_name,a.balance,a.purchased_total,a.spent_total FROM users u JOIN credit_accounts a ON a.user_id=u.id WHERE u.id=$1`,[userId]);return rows[0]}
async function getCreditState(userId){const account=await getUser(userId);const{rows}=await pool.query(`SELECT id,delta,reason,provider,model,created_at FROM credit_ledger WHERE user_id=$1 ORDER BY created_at DESC LIMIT 30`,[userId]);return{balance:Number(account?.balance||0),spent:Number(account?.spent_total||0),purchased:Number(account?.purchased_total||0),entries:rows.map(r=>({id:r.id,delta:Number(r.delta),reason:r.reason,provider:r.provider||undefined,model:r.model||undefined,createdAt:new Date(r.created_at).toISOString()}))}}
async function debitCredits(userId,amount,meta){const client=await pool.connect();const ledgerId=crypto.randomUUID();try{await client.query('BEGIN');const locked=await client.query('SELECT balance FROM credit_accounts WHERE user_id=$1 FOR UPDATE',[userId]);if(!locked.rows[0]||Number(locked.rows[0].balance)<amount)throw Object.assign(new Error('Insufficient SnapFlow Cloud credits'),{status:402});await client.query('UPDATE credit_accounts SET balance=balance-$2,spent_total=spent_total+$2,updated_at=now() WHERE user_id=$1',[userId,amount]);await client.query(`INSERT INTO credit_ledger(id,user_id,delta,reason,provider,model) VALUES($1,$2,$3,$4,$5,$6)`,[ledgerId,userId,-amount,meta.reason,meta.provider,meta.model]);await client.query('COMMIT');return ledgerId}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}
async function annotateDebit(ledgerId,usage){try{await pool.query('UPDATE credit_ledger SET usage_json=$2 WHERE id=$1',[ledgerId,usage||null])}catch{}}
async function refundDebit(userId,amount,ledgerId,provider,model){const client=await pool.connect();try{await client.query('BEGIN');const exists=await client.query('SELECT 1 FROM credit_ledger WHERE external_id=$1',[`refund:${ledgerId}`]);if(!exists.rowCount){await client.query('UPDATE credit_accounts SET balance=balance+$2,spent_total=GREATEST(0,spent_total-$2),updated_at=now() WHERE user_id=$1',[userId,amount]);await client.query(`INSERT INTO credit_ledger(id,user_id,delta,reason,provider,model,external_id) VALUES($1,$2,$3,'AI call refund',$4,$5,$6)`,[crypto.randomUUID(),userId,amount,provider,model,`refund:${ledgerId}`])}await client.query('COMMIT')}catch(e){await client.query('ROLLBACK');console.error('[SnapFlow Cloud] credit refund failed',e)}finally{client.release()}}
async function creditPurchase(userId,amount,externalId){const client=await pool.connect();try{await client.query('BEGIN');const exists=await client.query('SELECT 1 FROM credit_ledger WHERE external_id=$1',[externalId]);if(!exists.rowCount){await client.query('UPDATE credit_accounts SET balance=balance+$2,purchased_total=purchased_total+$2,updated_at=now() WHERE user_id=$1',[userId,amount]);await client.query(`INSERT INTO credit_ledger(id,user_id,delta,reason,external_id) VALUES($1,$2,$3,'Stripe purchase',$4)`,[crypto.randomUUID(),userId,amount,externalId])}await client.query('COMMIT')}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}

async function providerAsk({provider,model,text,imageBase64,contextImageBase64,signal}){
  const dataUrl=b=>b?`data:image/png;base64,${b}`:''
  const request=async(url,init)=>{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),imageBase64||contextImageBase64?45_000:25_000);if(signal)signal.addEventListener('abort',()=>controller.abort(),{once:true});try{return await fetch(url,{...init,signal:controller.signal})}finally{clearTimeout(timer)}}
  if(provider==='openai'){const key=process.env.OPENAI_API_KEY;if(!key)throw Object.assign(new Error('Provider not configured'),{status:503});const r=await request('https://api.openai.com/v1/responses',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${key}`},body:JSON.stringify({model,max_output_tokens:4096,input:[{role:'user',content:[{type:'input_text',text},...(contextImageBase64?[{type:'input_image',image_url:dataUrl(contextImageBase64)}]:[]),...(imageBase64?[{type:'input_image',image_url:dataUrl(imageBase64)}]:[])]}]})});const j=await r.json();if(!r.ok)throw Object.assign(new Error(j?.error?.message||`OpenAI ${r.status}`),{status:r.status});const chunks=[];for(const item of j.output||[])for(const part of item.content||[])if(part.text)chunks.push(part.text);return{text:j.output_text||chunks.join('\n'),usage:{inputTokens:j.usage?.input_tokens,outputTokens:j.usage?.output_tokens,totalTokens:j.usage?.total_tokens},requestId:r.headers.get('x-request-id')||undefined}}
  if(provider==='anthropic'){const key=process.env.ANTHROPIC_API_KEY;if(!key)throw Object.assign(new Error('Provider not configured'),{status:503});const r=await request('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'content-type':'application/json','x-api-key':key,'anthropic-version':'2023-06-01'},body:JSON.stringify({model,max_tokens:4096,messages:[{role:'user',content:[...(contextImageBase64?[{type:'image',source:{type:'base64',media_type:'image/png',data:contextImageBase64}}]:[]),...(imageBase64?[{type:'image',source:{type:'base64',media_type:'image/png',data:imageBase64}}]:[]),{type:'text',text}]}]})});const j=await r.json();if(!r.ok)throw Object.assign(new Error(j?.error?.message||`Anthropic ${r.status}`),{status:r.status});return{text:(j.content||[]).filter(x=>x.type==='text').map(x=>x.text).join('\n'),usage:{inputTokens:j.usage?.input_tokens,outputTokens:j.usage?.output_tokens,totalTokens:(j.usage?.input_tokens||0)+(j.usage?.output_tokens||0)},requestId:r.headers.get('request-id')||undefined}}
  if(provider==='gemini'){const key=process.env.GEMINI_API_KEY;if(!key)throw Object.assign(new Error('Provider not configured'),{status:503});const r=await request(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:'POST',headers:{'content-type':'application/json','x-goog-api-key':key},body:JSON.stringify({contents:[{parts:[...(contextImageBase64?[{inlineData:{mimeType:'image/png',data:contextImageBase64}}]:[]),...(imageBase64?[{inlineData:{mimeType:'image/png',data:imageBase64}}]:[]),{text}]}]})});const j=await r.json();if(!r.ok)throw Object.assign(new Error(j?.error?.message||`Gemini ${r.status}`),{status:r.status});return{text:(j.candidates?.[0]?.content?.parts||[]).filter(x=>x.text).map(x=>x.text).join('\n'),usage:{inputTokens:j.usageMetadata?.promptTokenCount,outputTokens:j.usageMetadata?.candidatesTokenCount,totalTokens:j.usageMetadata?.totalTokenCount},requestId:r.headers.get('x-request-id')||undefined}}
  const map={xai:['XAI_API_KEY','https://api.x.ai/v1/chat/completions'],deepseek:['DEEPSEEK_API_KEY','https://api.deepseek.com/chat/completions'],openrouter:['OPENROUTER_API_KEY','https://openrouter.ai/api/v1/chat/completions']}
  if(map[provider]){const[env,url]=map[provider],key=process.env[env];if(!key)throw Object.assign(new Error('Provider not configured'),{status:503});const supportsImage=provider!=='deepseek';const content=supportsImage&&(imageBase64||contextImageBase64)?[{type:'text',text},...(contextImageBase64?[{type:'image_url',image_url:{url:dataUrl(contextImageBase64)}}]:[]),...(imageBase64?[{type:'image_url',image_url:{url:dataUrl(imageBase64)}}]:[])]:text;const r=await request(url,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${key}`,...(provider==='openrouter'?{'X-Title':'SnapFlow Cloud'}:{})},body:JSON.stringify({model,max_tokens:4096,messages:[{role:'user',content}]})});const j=await r.json();if(!r.ok)throw Object.assign(new Error(j?.error?.message||`${provider} ${r.status}`),{status:r.status});return{text:j.choices?.[0]?.message?.content||'',usage:{inputTokens:j.usage?.prompt_tokens,outputTokens:j.usage?.completion_tokens,totalTokens:j.usage?.total_tokens},requestId:r.headers.get('x-request-id')||undefined}}
  throw Object.assign(new Error('Provider not supported by cloud'),{status:400})
}
async function providerModels(provider){const configs={openai:['OPENAI_API_KEY','https://api.openai.com/v1/models'],anthropic:['ANTHROPIC_API_KEY','https://api.anthropic.com/v1/models'],gemini:['GEMINI_API_KEY','https://generativelanguage.googleapis.com/v1beta/models?pageSize=1000'],xai:['XAI_API_KEY','https://api.x.ai/v1/models'],deepseek:['DEEPSEEK_API_KEY','https://api.deepseek.com/models'],openrouter:['OPENROUTER_API_KEY','https://openrouter.ai/api/v1/models']};const c=configs[provider];if(!c||!process.env[c[0]])return[];const headers=provider==='anthropic'?{'x-api-key':process.env[c[0]],'anthropic-version':'2023-06-01'}:provider==='gemini'?{'x-goog-api-key':process.env[c[0]]}:{authorization:`Bearer ${process.env[c[0]]}`};const r=await fetch(c[1],{headers,signal:AbortSignal.timeout(15_000)});if(!r.ok)return[];const j=await r.json();const arr=provider==='gemini'?j.models:j.data;return(Array.isArray(arr)?arr:[]).map(x=>({id:String(x.id||x.name||'').replace(/^models\//,''),name:x.display_name||x.displayName||x.name||x.id,vision:provider==='deepseek'?false:undefined})).filter(x=>x.id)}
function stripeSignatureOk(raw,signature){const secret=process.env.STRIPE_WEBHOOK_SECRET||'';if(!secret)return false;const values={};for(const part of String(signature||'').split(',')){const [k,...rest]=part.split('=');if(k&&rest.length)(values[k]??=[]).push(rest.join('='))}const t=values.t?.[0],sigs=values.v1||[];if(!t||!sigs.length||Math.abs(Date.now()/1000-Number(t))>300)return false;const expected=crypto.createHmac('sha256',secret).update(`${t}.${raw}`).digest('hex');return sigs.some(v=>safeEqualText(expected,v))}
async function stripeCheckout(userId,credits){const secret=process.env.STRIPE_SECRET_KEY;if(!secret)throw Object.assign(new Error('Stripe is not configured'),{status:503});const amount=Math.max(100,Math.min(100000,Math.round(Number(credits)||0)));const totalCents=Math.max(100,Math.round(amount*CENTS_PER_CREDIT));const success=process.env.STRIPE_SUCCESS_URL,cancel=process.env.STRIPE_CANCEL_URL;if(!success||!cancel)throw Object.assign(new Error('Stripe success/cancel URLs are not configured'),{status:503});const form=new URLSearchParams();form.set('mode','payment');form.set('success_url',success);form.set('cancel_url',cancel);form.set('line_items[0][price_data][currency]',process.env.STRIPE_CURRENCY||'usd');form.set('line_items[0][price_data][product_data][name]',`${amount} SnapFlow Credits`);form.set('line_items[0][price_data][unit_amount]',String(totalCents));form.set('line_items[0][quantity]','1');form.set('metadata[user_id]',userId);form.set('metadata[credits]',String(amount));const r=await fetch('https://api.stripe.com/v1/checkout/sessions',{method:'POST',headers:{authorization:`Bearer ${secret}`,'content-type':'application/x-www-form-urlencoded'},body:form,signal:AbortSignal.timeout(20_000)});const j=await r.json();if(!r.ok)throw Object.assign(new Error(j?.error?.message||'Stripe checkout failed'),{status:r.status});return{url:j.url,sessionId:j.id}}

const server=http.createServer(async(req,res)=>{
  const requestId=crypto.randomUUID();res.setHeader('x-request-id',requestId)
  const origin=process.env.CORS_ORIGIN||'';const cors=origin?{'access-control-allow-origin':origin,'access-control-allow-headers':'authorization,content-type,stripe-signature','access-control-allow-methods':'GET,POST,OPTIONS'}:{}
  if(req.method==='OPTIONS')return json(res,204,{},cors)
  try{
    const url=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`),ip=clientIp(req)
    if(url.pathname==='/health')return json(res,200,{ok:true,version:VERSION,providers:configuredProviders()},cors)
    if(url.pathname==='/v1/stripe/webhook'&&req.method==='POST'){const chunks=[];for await(const c of req)chunks.push(c);const raw=Buffer.concat(chunks).toString('utf8');if(!stripeSignatureOk(raw,req.headers['stripe-signature']))return json(res,400,{message:'Invalid Stripe signature',requestId},cors);const event=JSON.parse(raw);if(event.type==='checkout.session.completed'){const session=event.data?.object,userId=String(session?.metadata?.user_id||''),credits=Number(session?.metadata?.credits||0);if(userId&&credits>0)await creditPurchase(userId,credits,String(session.id))}return json(res,200,{received:true},cors)}
    if(url.pathname.startsWith('/v1/auth/'))enforceRate(`auth:${ip}`,AUTH_LIMIT_PER_15M,15*60_000)
    if(url.pathname==='/v1/auth/register'&&req.method==='POST'){const b=await body(req);const email=validateEmail(b.email),password=validatePassword(b.password),displayName=String(b.displayName||'').trim().slice(0,80);if(!displayName)throw Object.assign(new Error('Display name is required'),{status:400});const id=crypto.randomUUID(),salt=crypto.randomBytes(16).toString('hex'),hash=hashPassword(password,salt),client=await pool.connect();try{await client.query('BEGIN');await client.query('INSERT INTO users(id,email,display_name,password_hash,password_salt) VALUES($1,$2,$3,$4,$5)',[id,email,displayName,hash,salt]);await client.query('INSERT INTO credit_accounts(user_id,balance) VALUES($1,100)',[id]);await client.query(`INSERT INTO credit_ledger(id,user_id,delta,reason) VALUES($1,$2,100,'Welcome credits')`,[crypto.randomUUID(),id]);await client.query('COMMIT')}catch(e){await client.query('ROLLBACK');if(e.code==='23505')throw Object.assign(new Error('Email already registered'),{status:409});throw e}finally{client.release()}return json(res,201,{token:signToken(id)},cors)}
    if(url.pathname==='/v1/auth/login'&&req.method==='POST'){const b=await body(req);const email=validateEmail(b.email),password=validatePassword(b.password);const{rows}=await pool.query('SELECT id,password_hash,password_salt FROM users WHERE email=$1',[email]);const u=rows[0];if(!u||!passwordMatches(password,u.password_salt,u.password_hash))throw Object.assign(new Error('Invalid email or password'),{status:401});return json(res,200,{token:signToken(u.id)},cors)}
    const userId=authUser(req);if(!userId)return json(res,401,{message:'Authentication required',requestId},cors)
    enforceRate(`api:${userId}`,API_LIMIT_PER_MIN,60_000)
    if(url.pathname==='/v1/me'&&req.method==='GET'){const u=await getUser(userId);if(!u)return json(res,404,{message:'User not found',requestId},cors);return json(res,200,{user:{id:u.id,email:u.email,displayName:u.display_name},credits:Number(u.balance||0)},cors)}
    if(url.pathname==='/v1/credits'&&req.method==='GET')return json(res,200,await getCreditState(userId),cors)
    if(url.pathname==='/v1/providers'&&req.method==='GET')return json(res,200,{providers:configuredProviders().map(id=>({id,creditsPerCall:providerCreditCost(id)}))},cors)
    const modelMatch=url.pathname.match(/^\/v1\/providers\/([^/]+)\/models$/);if(modelMatch&&req.method==='GET')return json(res,200,{models:await providerModels(decodeURIComponent(modelMatch[1]))},cors)
    if(url.pathname==='/v1/ai/ask'&&req.method==='POST'){const b=await body(req);const provider=String(b.provider||''),model=String(b.model||'').slice(0,200),text=String(b.text||'').slice(0,100000);if(!configuredProviders().includes(provider))throw Object.assign(new Error('Provider is not configured on SnapFlow Cloud'),{status:503});if(!model)throw Object.assign(new Error('Model is required'),{status:400});const charge=providerCreditCost(provider),ledgerId=await debitCredits(userId,charge,{reason:`${provider} · ${String(b.action||'ask').slice(0,100)}`,provider,model});try{const result=await providerAsk({provider,model,text,imageBase64:b.imageBase64,contextImageBase64:b.contextImageBase64});await annotateDebit(ledgerId,result.usage);return json(res,200,{...result,creditsCharged:charge,requestId:result.requestId||requestId},cors)}catch(error){await refundDebit(userId,charge,ledgerId,provider,model);throw error}}
    if(url.pathname==='/v1/billing/checkout'&&req.method==='POST'){const b=await body(req);return json(res,200,await stripeCheckout(userId,b.credits),cors)}
    if(url.pathname==='/v1/cards/sync'&&req.method==='POST'){const b=await body(req,5*1024*1024),cards=Array.isArray(b.cards)?b.cards.slice(0,500):[],client=await pool.connect();try{await client.query('BEGIN');for(const c of cards){const id=String(c?.id||'').slice(0,160);if(!id)continue;const payload={...c,screenshotPath:'',thumbnailPath:'',imageBytes:undefined};await client.query(`INSERT INTO synced_cards(user_id,card_id,payload,updated_at) VALUES($1,$2,$3,now()) ON CONFLICT(user_id,card_id) DO UPDATE SET payload=EXCLUDED.payload,updated_at=now()`,[userId,id,payload])}await client.query('COMMIT')}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}return json(res,200,{ok:true,count:cards.length},cors)}
    return json(res,404,{message:'Not found',requestId},cors)
  }catch(error){const status=Math.min(599,Math.max(400,Number(error?.status||500)));if(status>=500)console.error('[SnapFlow Cloud]',requestId,error);const headers={...cors,...(error?.retryAfterMs?{'retry-after':String(Math.ceil(error.retryAfterMs/1000))}:{})};return json(res,status,{message:status>=500?'Server error':String(error?.message||error),requestId,...(error?.retryAfterMs?{retryAfterMs:error.retryAfterMs}:{})},headers)}
})
server.requestTimeout=60_000
server.headersTimeout=20_000
server.listen(PORT,()=>console.log(`SnapFlow Cloud ${VERSION} listening on :${PORT}`))
