import fs from 'node:fs'
import type { AiUsage, ProviderId, ProviderModelOption, ProviderTestResult } from '../../shared/types'
import { ProviderRegistry, providerDescriptors } from './registry'
import { encryptSecret, providerHasCredential as localProviderHasCredential, getProviderSecret } from './secrets'
import { cloudService } from '../cloud'
import { store } from '../store'
import { redactSensitiveText } from '../../shared/privacy'
import { classifyProviderError } from '../../shared/errors'
import { imageHash, writeProviderAudit } from '../audit-log'

export type ProviderResult = { text: string; usage?: AiUsage; model: string; isMock?: boolean; requestId?: string; latencyMs?: number }
function tr(zh: string, en: string) { return store.getSettings().locale === 'en-US' ? en : zh }
function readImage(file?: string) { return file && fs.existsSync(file) ? fs.readFileSync(file) : undefined }

export { encryptSecret, providerDescriptors, ProviderRegistry }
export function providerHasCredential(provider: ProviderId) {
  return localProviderHasCredential(provider) || cloudService.canUseProviderSync(provider)
}
export function providerUsesCloud(provider: ProviderId) {
  return !localProviderHasCredential(provider) && cloudService.canUseProviderSync(provider)
}

export function callMockProvider(args: { prompt: string; ocrText?: string }): ProviderResult {
  const visible = redactSensitiveText((args.ocrText || '').trim(), { email: store.getSettings().privacy.autoMaskEmail, phone: store.getSettings().privacy.autoMaskPhone })
  const excerpt = visible ? visible.slice(0, 900) : tr('（当前没有可用 OCR 文本）', '(No OCR text is currently available.)')
  const text = store.getSettings().locale === 'en-US'
    ? `【Demo Mode / Mock】\nThis answer was NOT generated by a real AI provider.\n\nTask: ${args.prompt.slice(0, 240)}\n\nVisible text:\n${excerpt}\n\nConfigure a Provider in Settings → AI Providers, or enable a reachable Ollama model.`
    : `【演示模式 / Mock】\n这不是任何真实 AI Provider 生成的回答。\n\n任务：${args.prompt.slice(0, 240)}\n\n可见文字：\n${excerpt}\n\n请在 Settings → AI Providers 配置 Provider，或启用可访问的 Ollama 本地模型。`
  return { text, model: 'SnapFlow Demo Mock', isMock: true }
}

export async function callProvider(args: { provider: ProviderId; model?: string; prompt: string; screenshotPath: string; contextScreenshotPath?: string; ocrText?: string; action?: string; signal?: AbortSignal }): Promise<ProviderResult> {
  const adapter = ProviderRegistry.byId(args.provider)
  if (!adapter) throw new Error(`Unsupported provider: ${args.provider}`)
  const cfg = store.getSettings().providers[args.provider]
  const model = args.model || cfg.model
  let image = cfg.supportsVision ? readImage(args.screenshotPath) : undefined
  let contextImage = cfg.supportsVision ? readImage(args.contextScreenshotPath) : undefined
  const privacy = store.getSettings().privacy
  const rawOcr = args.ocrText || ''
  const redactedOcr = redactSensitiveText(rawOcr, { email: privacy.autoMaskEmail, phone: privacy.autoMaskPhone })
  const sensitiveDetected = redactedOcr !== rawOcr
  // Without OCR bounding boxes, pretending to pixel-mask just the email/phone would be unsafe.
  // In the conservative path SnapFlow withholds the raw image and sends only redacted OCR.
  if (sensitiveDetected && (privacy.autoMaskEmail || privacy.autoMaskPhone)) {
    image = undefined
    contextImage = undefined
  }
  const privacyNotice = sensitiveDetected
    ? tr('\n\n隐私提示：检测到已启用遮挡的敏感文字，原始截图未发送给远程 AI，仅提供脱敏 OCR。', '\n\nPrivacy notice: sensitive text matched an enabled masking rule. The raw screenshot was withheld from the remote AI and only redacted OCR was provided.')
    : ''
  const text = image?.length
    ? args.prompt
    : `${args.prompt}${redactedOcr ? `\n\nOCR text:\n${redactedOcr}` : ''}${privacyNotice}`

  if (providerUsesCloud(args.provider)) {
    const started = Date.now()
    let status: 'ok' | 'error' = 'ok'
    let requestId: string | undefined
    let httpStatus: number | undefined
    let usage: AiUsage | undefined
    let errorCode: ReturnType<typeof classifyProviderError>['code'] | undefined
    try {
      const result = await cloudService.ask({ provider: args.provider, model, text, image, contextImage, action: args.action, signal: args.signal })
      requestId = result.requestId
      usage = result.usage
      return { text: result.text, usage: result.usage, model, requestId, latencyMs: Date.now() - started }
    } catch (error) {
      status = 'error'
      const normalized = classifyProviderError(error)
      requestId = normalized.requestId
      httpStatus = normalized.httpStatus
      errorCode = normalized.code
      throw normalized
    } finally {
      writeProviderAudit({
        ts: new Date().toISOString(), provider: args.provider, model, action: args.action || 'ask', status,
        latencyMs: Date.now() - started, httpStatus, errorCode, requestId, promptTokens: usage?.inputTokens, completionTokens: usage?.outputTokens,
        vision: Boolean(image?.length), imageHash: imageHash(image), textSnippetRedacted: text
      })
    }
  }

  let output = '', usage: AiUsage | undefined
  const started = Date.now()
  for await (const delta of adapter.ask({ model, text, image, contextImage, action: args.action || 'ask', signal: args.signal })) {
    if (delta.type === 'text') output += delta.text || ''
    if (delta.type === 'usage') usage = delta.usage
  }
  return { text: output, usage, model, latencyMs: Date.now() - started }
}
export async function listProviderModels(provider: ProviderId): Promise<ProviderModelOption[]> {
  const adapter = ProviderRegistry.byId(provider); if (!adapter) throw new Error(`Unsupported provider: ${provider}`)
  if (!localProviderHasCredential(provider) && await cloudService.canUseProvider(provider)) return cloudService.listModels(provider)
  return adapter.listModels()
}
export async function testProvider(provider: ProviderId): Promise<ProviderTestResult> {
  const adapter = ProviderRegistry.byId(provider); if (!adapter) throw new Error(`Unsupported provider: ${provider}`)
  if (!localProviderHasCredential(provider) && await cloudService.canUseProvider(provider)) {
    const started = Date.now()
    const model = store.getSettings().providers[provider].model
    try {
      const result = await callProvider({ provider, model, prompt: 'Reply with exactly: SNAPFLOW_OK', screenshotPath: '', action: 'test_connection' })
      return { ok: Boolean(result.text.trim()), provider, model: result.model, message: 'Connected via SnapFlow Cloud', latencyMs: Date.now() - started, requestId: result.requestId }
    } catch (error) {
      const normalized = classifyProviderError(error)
      return { ok: false, provider, model, message: normalized.message, latencyMs: Date.now() - started, requestId: normalized.requestId, errorCode: normalized.code }
    }
  }
  return adapter.testConnection()
}
