const fs = require('node:fs')
const path = require('node:path')
const { spawnSync } = require('node:child_process')
const root = process.cwd()
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'))
let ok = true
function check(label, condition, detail = '') { console.log(`${condition ? 'PASS' : 'FAIL'}  ${label}${detail ? ` — ${detail}` : ''}`); ok = Boolean(condition) && ok }
function exists(rel) { return fs.existsSync(path.join(root, rel)) }
function source(rel) { return exists(rel) ? fs.readFileSync(path.join(root, rel), 'utf8') : '' }
check('package version', /^\d+\.\d+\.\d+$/.test(pkg.version), pkg.version)
check('main entry', pkg.main === './out/main/index.js', pkg.main)
check('login page', exists('src/renderer/src/components/LoginPage.tsx'))
check('language module', exists('src/renderer/src/i18n.tsx'))
check('provider registry', exists('src/main/providers/base.ts') && exists('src/main/providers/registry.ts') && exists('src/main/providers/index.ts'))
check('provider setup guide', exists('PROVIDER_SETUP.md'))
check('owner guide', exists('OWNER_GUIDE.md'))
check('release checklist', exists('RELEASE_CHECKLIST.md'))
check('WorkBuddy handoff', exists('WORKBUDDY_HANDOFF.md'))
check('Windows builder', exists('BUILD_WINDOWS.cmd') && exists('scripts/build-windows.ps1'))
check('Electron verified fallback', exists('scripts/install-electron-windows.ps1'))
check('packaged smoke test', exists('scripts/smoke-windows.ps1'))
check('cloud gateway', exists('cloud-server/server.mjs') && exists('cloud-server/schema.sql'))
check('visual knowledge modules', exists('src/shared/semantic.ts') && exists('src/shared/workflow.ts') && exists('src/shared/privacy.ts'))
check('skill marketplace', exists('src/main/skill-marketplace.ts') && exists('resources/skill-marketplace.json'))
check('local OCR', exists('src/main/local-ocr.ts') && exists('src/renderer/src/workers/ocr.worker.ts'))
check('updater', exists('src/main/updater.ts') && Boolean(pkg.dependencies?.['electron-updater']))
check('website', exists('snapflow-website/index.html') && exists('scripts/build-website.cjs'))
const targets = JSON.stringify(pkg.build?.win?.target || [])
check('NSIS target', targets.includes('nsis'))
check('Portable target', targets.includes('portable'))
check('normal tsconfig has no validation shim', !exists('src/validation-shims.d.ts'))
const providerSource = source('src/main/providers/index.ts')
check('live model discovery contract', /export async function listProviderModels/.test(providerSource))
check('real provider test contract', /export async function testProvider/.test(providerSource))
const secretsSource = source('src/main/providers/secrets.ts')
check('safeStorage provider secrets', /safeStorage/.test(secretsSource) && !/localStorage/.test(secretsSource))
const i18nSource = source('src/renderer/src/i18n.tsx')
check('Chinese/English locale contract', i18nSource.includes('zh-CN') && i18nSource.includes('en-US') && i18nSource.includes('LanguageSwitch'))
const mainSource = source('src/main/index.ts')
check('semantic IPC', mainSource.includes("card:search-semantic"))
check('workflow IPC', mainSource.includes("workflow:recommendations") && mainSource.includes("workflow:create"))
check('cloud IPC', mainSource.includes("cloud:login") && mainSource.includes("cloud:checkout"))
check('marketplace IPC', mainSource.includes("skill:marketplace-list"))
check('update IPC', mainSource.includes("update:check") && mainSource.includes("update:download"))
const ipc = spawnSync(process.execPath, [path.join(root, 'scripts', 'verify-ipc.cjs')], { cwd: root, stdio: 'inherit' })
check('IPC contract', ipc.status === 0)
if (!ok) process.exit(1)
