const fs = require('node:fs')
const path = require('node:path')
const root = process.cwd()
const preload = fs.readFileSync(path.join(root, 'src', 'preload', 'index.ts'), 'utf8')
const mainDir=path.join(root,'src','main')
const main = fs.readdirSync(mainDir).filter(x=>x.endsWith('.ts')).map(x=>fs.readFileSync(path.join(mainDir,x),'utf8')).join('\n')
const index = fs.readFileSync(path.join(mainDir,'index.ts'),'utf8')
const invoked = new Set([...preload.matchAll(/ipcRenderer\.invoke\(['"]([^'"]+)['"]/g)].map((m) => m[1]))
const handled = new Set([...index.matchAll(/protectedHandle\(['"]([^'"]+)['"]/g),...index.matchAll(/ipcMain\.handle\(['"]([^'"]+)['"]/g)].map((m) => m[1]))
const listened = new Set([...preload.matchAll(/ipcRenderer\.on\(['"]([^'"]+)['"]/g)].map((m) => m[1]))
const sent = new Set([...main.matchAll(/notifyAll\(['"]([^'"]+)['"]/g),...main.matchAll(/sendToMainWhenReady\(['"]([^'"]+)['"]/g),...main.matchAll(/webContents\.send\(['"]([^'"]+)['"]/g)].map((m) => m[1]))
const missingHandlers=[...invoked].filter(x=>!handled.has(x)).sort(), missingEvents=[...listened].filter(x=>!sent.has(x)).sort()
console.log(`IPC invoke channels: ${invoked.size}; handlers: ${handled.size}`)
console.log(`IPC event listeners: ${listened.size}; send sites: ${sent.size}`)
if(missingHandlers.length)console.error('Missing main handlers:',missingHandlers.join(', '))
if(missingEvents.length)console.error('Missing main event senders:',missingEvents.join(', '))
if(missingHandlers.length||missingEvents.length)process.exit(1)
console.log('PASS  IPC preload/main symmetry')
